project:
  render:
    - "*.qmd"      # Render all Quarto markdown files
    - "!data-raw/" # Exclude anything in the data-raw directory
author: "UC Davis Seroepidemiology Research Group (UCD-SERG)"
date: '`r Sys.Date()`'
format:
  html:
    number-sections: true
    toc: true
    html-math-method: mathjax
    fig-cap-location: top
    echo: false
  revealjs:
    reference-location: document
    echo: false
    html-math-method: mathjax
    scrollable: true
    auto-stretch: true
    fig-height: 3
    fig-width: 7
    number-sections: true
    number-depth: 2
    fig-cap-location: top
  pptx:
    number-sections: false
    slide-level: 2
    reference-location: document
    # reference-doc: vignettes/articles/templates/Gates_template.pptx
  docx:
    number-sections: true
    toc: true
    reference-location: document
bibliography: vignettes/references.bib
