project:
  render: ['*.qmd']
author: "UC Davis Seroepidemiology Research Group (UCD-SERG)"
date: '`r Sys.Date()`'
format:
  pptx: default
    # reference-doc: vignettes/articles/templates/Gates_template.pptx
  html:
    number-sections: true
    toc: true
    html-math-method: mathjax
    fig-cap-location: top
    echo: false
  revealjs:
    echo: false
    html-math-method: mathjax
    scrollable: true
    auto-stretch: true
    fig-height: 3
    fig-width: 7
    number-sections: true
    number-depth: 2
    fig-cap-location: top
bibliography: vignettes/references.bib
